global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.HttpOverrides;
global using Microsoft.AspNetCore.Identity;
global using MudBlazor.Services;
global using RegistroServizi.Application;
global using RegistroServizi.Data;
global using RegistroServizi.Data.Identity;
global using RegistroServizi.Web.Components;
global using RegistroServizi.Web.Components.Account;